### ISSUE TITLE
Stop Running system-bridge before Installation

### ISSUE THREAD

**Issue by dlangerm** [timmo001/system-bridge#858] opened 2021-09-25 18:03 UTC
### Description

If system bridge is running during installation, the install fails and allows manual intervention to retry the install. The installer should just check if system bridge is running and close it before attempting to install a new version.

### What Platform / OS are you running?

Windows

### What version are you running?

2.7

**Comment by timmo001** [comment] 2021-09-25 20:31
Duplicate of #462

**Closed by timmo001** 2021-09-25 20:31 UTC
